apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service         
spec:
  selector:
    app: wil-playground  
  type: NodePort           
  ports:
  - port: 8888           
    targetPort: 8888  
    nodePort: 30080
